### ISSUE TITLE
Error when autopilot to Seed

### ISSUE THREAD

**Issue by Prontius** [NordLandeW/DSPMod-N#2] opened 2024-09-26 15:00 UTC
Thanks a lot for the mod. I set it up with Thunderstore Mod Manager but I have an error when targeting Dark Fog Seeds. Autopilot to planets worked fine.

![image](https://github.com/user-attachments/assets/01af34aa-ecac-4f96-bd2b-cc3aa793df25)

How I can recreate the issue:
Load my save, double click on a seed from map view OR click to navigate to seed from star list. Error appears after taking off from planet and aiming toward seed, before entering warp.

Mods used through Thunderstore Mod Manager:
BepInEx v5.4.17
CAAP_N v1.3.0

Game version:
0.10.30.23430 (latest)

I uploaded my save to mega:
https://mega.nz/file/BxEHkaTI#T-1LQamAnFEN8o3E-MyGWz_M_nU_9amerb3bxbvekmc

**Comment by Prontius** [comment] 2024-09-26 16:10
I installed ErrorAnalyzer mod and it's dependency IlLine so I can copy the text of the error:

```ini
An error has occurred! Game version 0.10.30.23430
4 Mods used: [ErrorAnalyzer1.2.2] [IlLine1.0.0] [CruiseAssist-N1.3.0] [Autopilot-N1.3.0] 
NullReferenceException: Object reference not set to an instance of an object
tanu.AutoPilot.AutoPilotExtension.OperateSail (PlayerMove_Sail __instance);(IL_01DA)
Patch_PlayerMoveSail+<>c__DisplayClass0_0.<GameTick_Prefix>b__1 (tanu.CruiseAssist.CruiseAssistExtensionAPI extension);(IL_0000)
System.Collections.Generic.List`1[T].ForEach (System.Action`1[T] action);(IL_0024)
Patch_PlayerMoveSail.GameTick_Prefix (PlayerMove_Sail __instance);(IL_0121)
PlayerMove_Sail.GameTick (System.Int64 timei);(IL_0005)
PlayerController.GameTick (System.Int64 time);(IL_006C)
Player.GameTick (System.Int64 time);(IL_0020)
GameData.GameTick (System.Int64 time);(IL_0169)
GameMain.FixedUpdate ();(IL_015A)
[== Mod patches on the stack ==]
void Patch_PlayerMoveSail::GameTick_Prefix(PlayerMove_Sail __instance); GameTick(Prefix)
```

**Comment by Prontius** [comment] 2024-09-27 08:25
I fixed it! In Cruise Assist Config, disable "Mark the visited system and planet". It must have been trying to mark the seed but that wasn't possible.
![image](https://github.com/user-attachments/assets/a1a7d6f8-afc3-459b-b8ae-1eec3c7a853c)

**Comment by NordLandeW** [comment] 2024-10-05 05:56
Thank you for reporting that! I'll try fixing this issue. :)

**Comment by NordLandeW** [comment] 2024-10-05 15:18
Looks like the issue was caused by some leftover code logic leading to a basic mistake. It's a little bit weird that I can't reproduce the error on my side. Still I've made the corrections, and I hope this problem is now fixed :) https://github.com/NagaseIori/DSPMod-N/commit/2c9b5cbc55145aff7e6ba817b2995f432ddbd4d9

**Closed as completed by NordLandeW** 2024-10-05 15:18 UTC

**Comment by Prontius** [comment] 2024-10-05 15:37
Awesome. I can't reproduce the error with the updated version. Thanks a lot.
